# This is a Check Point CloudGuard ShiftLeft Demo pipeline
# In this pipeline we will run through a terraform scan, container image scan
# and a repository scan.

jobs:
- job:  ContainerImageScan
  pool:
    vmImage: 'ubuntu-latest'

steps:
  - task: DockerInstaller
    inputs:
      dockerVersion: '17.09.0-ce'
    displayName: Installing Docker